/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InsuranceAgentService } from "../insuranceAgent.service";
import { InsuranceAgentCreateInput } from "./InsuranceAgentCreateInput";
import { InsuranceAgent } from "./InsuranceAgent";
import { InsuranceAgentFindManyArgs } from "./InsuranceAgentFindManyArgs";
import { InsuranceAgentWhereUniqueInput } from "./InsuranceAgentWhereUniqueInput";
import { InsuranceAgentUpdateInput } from "./InsuranceAgentUpdateInput";
import { InsurancePolicyFindManyArgs } from "../../insurancePolicy/base/InsurancePolicyFindManyArgs";
import { InsurancePolicy } from "../../insurancePolicy/base/InsurancePolicy";
import { InsurancePolicyWhereUniqueInput } from "../../insurancePolicy/base/InsurancePolicyWhereUniqueInput";

export class InsuranceAgentControllerBase {
  constructor(protected readonly service: InsuranceAgentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InsuranceAgent })
  async createInsuranceAgent(
    @common.Body() data: InsuranceAgentCreateInput
  ): Promise<InsuranceAgent> {
    return await this.service.createInsuranceAgent({
      data: data,
      select: {
        agencyName: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [InsuranceAgent] })
  @ApiNestedQuery(InsuranceAgentFindManyArgs)
  async insuranceAgents(
    @common.Req() request: Request
  ): Promise<InsuranceAgent[]> {
    const args = plainToClass(InsuranceAgentFindManyArgs, request.query);
    return this.service.insuranceAgents({
      ...args,
      select: {
        agencyName: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InsuranceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async insuranceAgent(
    @common.Param() params: InsuranceAgentWhereUniqueInput
  ): Promise<InsuranceAgent | null> {
    const result = await this.service.insuranceAgent({
      where: params,
      select: {
        agencyName: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InsuranceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInsuranceAgent(
    @common.Param() params: InsuranceAgentWhereUniqueInput,
    @common.Body() data: InsuranceAgentUpdateInput
  ): Promise<InsuranceAgent | null> {
    try {
      return await this.service.updateInsuranceAgent({
        where: params,
        data: data,
        select: {
          agencyName: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InsuranceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInsuranceAgent(
    @common.Param() params: InsuranceAgentWhereUniqueInput
  ): Promise<InsuranceAgent | null> {
    try {
      return await this.service.deleteInsuranceAgent({
        where: params,
        select: {
          agencyName: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/insurancePolicies")
  @ApiNestedQuery(InsurancePolicyFindManyArgs)
  async findInsurancePolicies(
    @common.Req() request: Request,
    @common.Param() params: InsuranceAgentWhereUniqueInput
  ): Promise<InsurancePolicy[]> {
    const query = plainToClass(InsurancePolicyFindManyArgs, request.query);
    const results = await this.service.findInsurancePolicies(params.id, {
      ...query,
      select: {
        coverageAmount: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        effectiveDate: true,
        expiryDate: true,
        id: true,

        insuranceAgent: {
          select: {
            id: true,
          },
        },

        policyNumber: true,
        premiumAmount: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/insurancePolicies")
  async connectInsurancePolicies(
    @common.Param() params: InsuranceAgentWhereUniqueInput,
    @common.Body() body: InsurancePolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      insurancePolicies: {
        connect: body,
      },
    };
    await this.service.updateInsuranceAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/insurancePolicies")
  async updateInsurancePolicies(
    @common.Param() params: InsuranceAgentWhereUniqueInput,
    @common.Body() body: InsurancePolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      insurancePolicies: {
        set: body,
      },
    };
    await this.service.updateInsuranceAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/insurancePolicies")
  async disconnectInsurancePolicies(
    @common.Param() params: InsuranceAgentWhereUniqueInput,
    @common.Body() body: InsurancePolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      insurancePolicies: {
        disconnect: body,
      },
    };
    await this.service.updateInsuranceAgent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
