/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Claim } from "./Claim";
import { ClaimCountArgs } from "./ClaimCountArgs";
import { ClaimFindManyArgs } from "./ClaimFindManyArgs";
import { ClaimFindUniqueArgs } from "./ClaimFindUniqueArgs";
import { CreateClaimArgs } from "./CreateClaimArgs";
import { UpdateClaimArgs } from "./UpdateClaimArgs";
import { DeleteClaimArgs } from "./DeleteClaimArgs";
import { InsurancePolicy } from "../../insurancePolicy/base/InsurancePolicy";
import { ClaimService } from "../claim.service";
@graphql.Resolver(() => Claim)
export class ClaimResolverBase {
  constructor(protected readonly service: ClaimService) {}

  async _claimsMeta(
    @graphql.Args() args: ClaimCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Claim])
  async claims(@graphql.Args() args: ClaimFindManyArgs): Promise<Claim[]> {
    return this.service.claims(args);
  }

  @graphql.Query(() => Claim, { nullable: true })
  async claim(
    @graphql.Args() args: ClaimFindUniqueArgs
  ): Promise<Claim | null> {
    const result = await this.service.claim(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Claim)
  async createClaim(@graphql.Args() args: CreateClaimArgs): Promise<Claim> {
    return await this.service.createClaim({
      ...args,
      data: {
        ...args.data,

        insurancePolicy: args.data.insurancePolicy
          ? {
              connect: args.data.insurancePolicy,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Claim)
  async updateClaim(
    @graphql.Args() args: UpdateClaimArgs
  ): Promise<Claim | null> {
    try {
      return await this.service.updateClaim({
        ...args,
        data: {
          ...args.data,

          insurancePolicy: args.data.insurancePolicy
            ? {
                connect: args.data.insurancePolicy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Claim)
  async deleteClaim(
    @graphql.Args() args: DeleteClaimArgs
  ): Promise<Claim | null> {
    try {
      return await this.service.deleteClaim(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => InsurancePolicy, {
    nullable: true,
    name: "insurancePolicy",
  })
  async getInsurancePolicy(
    @graphql.Parent() parent: Claim
  ): Promise<InsurancePolicy | null> {
    const result = await this.service.getInsurancePolicy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
